### ISSUE TITLE
Please provide anciliary resources mentioned in the training. 

### ISSUE THREAD

**Issue by mukteshkrmishra** [sinanuozdemir/oreilly-pytorch-dl#1]

**Comment by sinanuozdemir** [comment]
So sorry I got caught up in the holidays! Here are some links I think will help.

- My Alignment code has an example of fine-tuning Llama 2 with both pre-training data and instruction data: https://github.com/sinanuozdemir/oreilly-llm-alignment
  - Here is another version of that code: https://github.com/sinanuozdemir/odsc-2023-llm-alignment
- Here is a more theoretical approach to building LLMs from scratch: https://towardsdatascience.com/how-to-build-an-llm-from-scratch-8c477768f1f9
- I haven't read this but I do trust this publisher! https://www.manning.com/books/build-a-large-language-model-from-scratch

If you have any further questions, please let me know :) As I think of more, I'll add them here
